"""second

Revision ID: 18091ade5943
Revises: db0cedd98a95
Create Date: 2020-04-25 13:41:06.091285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18091ade5943'
down_revision = 'db0cedd98a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('sento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sento', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
