"""May19

Revision ID: 3a008bcad9e3
Revises: 32e81a0c8d6d
Create Date: 2020-05-19 13:32:16.810850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a008bcad9e3'
down_revision = '32e81a0c8d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenum', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phonenum')

    # ### end Alembic commands ###
