"""nfirst

Revision ID: 726bc189f54b
Revises: db0cedd98a95_first
Create Date: 2020-05-06 16:33:42.341364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726bc189f54b'
down_revision = 'db0cedd98a95_first'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.INTEGER(),
               nullable=False,server_default="0")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
