"""May20

Revision ID: 76727e28a741
Revises: 1ad8d372f580
Create Date: 2020-05-20 08:33:35.812611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76727e28a741'
down_revision = '1ad8d372f580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
